import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | JT Dev Studio",
  description: "How JT Dev Studio collects, uses, and protects your information.",
};

const sections = [
  { id: "who-we-are", label: "1. Who We Are" },
  { id: "information-we-collect", label: "2. Information We Collect" },
  { id: "how-we-use", label: "3. How We Use Your Information" },
  { id: "third-parties", label: "4. Third-Party Services" },
  { id: "cookies", label: "5. Cookies" },
  { id: "data-retention", label: "6. Data Retention" },
  { id: "your-rights", label: "7. Your Rights" },
  { id: "governing-law", label: "8. Governing Law" },
  { id: "changes", label: "9. Changes to This Policy" },
];

export default function PrivacyPolicyPage() {
  return (
    <main className="min-h-screen bg-background text-foreground px-4 sm:px-8 py-16 max-w-7xl mx-auto">
      {/* Page Title */}
      <div className="mb-10">
        <h1 className="text-4xl font-bold text-[#DAA520]">Privacy Policy</h1>
        <p className="text-sm text-[#C0C0C0]/60 mt-2">Effective Date: July 1, 2026</p>
      </div>

      {/* Two-column layout on large screens */}
      <div className="lg:grid lg:grid-cols-[220px_1fr] lg:gap-12">

        {/* Sidebar TOC -- sticky on lg, hidden on mobile */}
        <aside className="hidden lg:block">
          <div className="sticky top-24 space-y-1">
            <p className="text-xs font-semibold uppercase tracking-widest text-[#DAA520]/70 mb-3">
              On this page
            </p>
            {sections.map((s) => (
              <a
                key={s.id}
                href={`#${s.id}`}
                className="block text-sm text-[#C0C0C0]/60 hover:text-[#DAA520] transition-colors py-1 border-l-2 border-transparent hover:border-[#DAA520] pl-3"
              >
                {s.label}
              </a>
            ))}
          </div>
        </aside>

        {/* Main content */}
        <article className="space-y-10 min-w-0">

          <section id="who-we-are">
            <h2 className="text-xl font-semibold text-[#DAA520]/90 mb-3">1. Who We Are</h2>
            <p className="text-[#C0C0C0]/80 leading-relaxed">
              JT Dev Studio is operated by Jesus Torres, a freelance software developer based in
              Texas. This site is located at{" "}
              <a href="https://jt-devstudio.tech" className="text-[#DAA520] hover:underline">
                jt-devstudio.tech
              </a>
              . For privacy-related questions, contact{" "}
              <a href="mailto:j.torres3.dev@gmail.com" className="text-[#DAA520] hover:underline">
                j.torres3.dev@gmail.com
              </a>
              .
            </p>
          </section>

          <section id="information-we-collect">
            <h2 className="text-xl font-semibold text-[#DAA520]/90 mb-3">2. Information We Collect</h2>
            <p className="text-[#C0C0C0]/80 leading-relaxed mb-3">
              We collect information you provide directly and information generated by your use of
              the site:
            </p>
            <ul className="list-disc list-inside text-[#C0C0C0]/80 space-y-2 leading-relaxed">
              <li>
                <span className="text-[#C0C0C0]">Account information</span> -- name, email address,
                and username when you create an account via email or GitHub OAuth.
              </li>
              <li>
                <span className="text-[#C0C0C0]">Payment information</span> -- when you make a
                donation or purchase a service, Stripe collects and processes your payment card
                details. We do not store full card numbers.
              </li>
              <li>
                <span className="text-[#C0C0C0]">Contact form submissions</span> -- your name,
                email, and message when you use the contact form.
              </li>
              <li>
                <span className="text-[#C0C0C0]">Usage data</span> -- aggregate, anonymized
                analytics collected by Vercel Analytics (no personally identifiable information is
                stored).
              </li>
              <li>
                <span className="text-[#C0C0C0]">User-generated content</span> -- posts, comments,
                and profile assets you upload to the platform.
              </li>
            </ul>
          </section>

          <section id="how-we-use">
            <h2 className="text-xl font-semibold text-[#DAA520]/90 mb-3">
              3. How We Use Your Information
            </h2>
            <ul className="list-disc list-inside text-[#C0C0C0]/80 space-y-2 leading-relaxed">
              <li>To authenticate you and manage your account.</li>
              <li>To process payments and donations through Stripe.</li>
              <li>To respond to contact and project inquiry submissions.</li>
              <li>To generate anonymized usage analytics to improve the site.</li>
              <li>To track resume download events tied to your account.</li>
            </ul>
          </section>

          <section id="third-parties">
            <h2 className="text-xl font-semibold text-[#DAA520]/90 mb-3">4. Third-Party Services</h2>
            <p className="text-[#C0C0C0]/80 leading-relaxed mb-3">
              We use the following third-party services. Each has its own privacy policy:
            </p>
            <ul className="list-disc list-inside text-[#C0C0C0]/80 space-y-2 leading-relaxed">
              <li>
                <a
                  href="https://stripe.com/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[#DAA520] hover:underline"
                >
                  Stripe
                </a>{" "}
                -- payment processing.
              </li>
              <li>
                <a
                  href="https://supabase.com/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[#DAA520] hover:underline"
                >
                  Supabase
                </a>{" "}
                -- authentication, database storage, and file storage.
              </li>
              <li>
                <a
                  href="https://vercel.com/legal/privacy-policy"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[#DAA520] hover:underline"
                >
                  Vercel
                </a>{" "}
                -- hosting and anonymized analytics.
              </li>
              <li>
                <a
                  href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-[#DAA520] hover:underline"
                >
                  GitHub
                </a>{" "}
                -- OAuth login (optional).
              </li>
            </ul>
          </section>

          <section id="cookies">
            <h2 className="text-xl font-semibold text-[#DAA520]/90 mb-3">5. Cookies</h2>
            <p className="text-[#C0C0C0]/80 leading-relaxed mb-3">
              This site uses the following cookies and local storage:
            </p>
            <ul className="list-disc list-inside text-[#C0C0C0]/80 space-y-2 leading-relaxed">
              <li>
                <span className="text-[#C0C0C0]">Supabase auth tokens</span> -- stored in a secure
                cookie to keep you logged in. Required for authenticated features.
              </li>
              <li>
                <span className="text-[#C0C0C0]">Stripe session cookies</span> -- set during
                checkout to maintain your payment session.
              </li>
              <li>
                <span className="text-[#C0C0C0]">Vercel Analytics</span> -- no cookies with PII.
                Uses aggregated, anonymized signals only.
              </li>
            </ul>
          </section>

          <section id="data-retention">
            <h2 className="text-xl font-semibold text-[#DAA520]/90 mb-3">6. Data Retention</h2>
            <p className="text-[#C0C0C0]/80 leading-relaxed">
              Account data is retained until you delete your account. Contact form submissions are
              retained for up to 12 months for business correspondence purposes. Payment records are
              retained as required by Stripe and applicable tax law.
            </p>
          </section>

          <section id="your-rights">
            <h2 className="text-xl font-semibold text-[#DAA520]/90 mb-3">7. Your Rights</h2>
            <p className="text-[#C0C0C0]/80 leading-relaxed">
              You may delete your account at any time from the Settings page, which removes your
              profile and associated data. To request deletion of contact form submissions or other
              data, email{" "}
              <a href="mailto:j.torres3.dev@gmail.com" className="text-[#DAA520] hover:underline">
                j.torres3.dev@gmail.com
              </a>
              .
            </p>
          </section>

          <section id="governing-law">
            <h2 className="text-xl font-semibold text-[#DAA520]/90 mb-3">8. Governing Law</h2>
            <p className="text-[#C0C0C0]/80 leading-relaxed">
              This Privacy Policy is governed by the laws of the State of Texas, United States.
            </p>
          </section>

          <section id="changes">
            <h2 className="text-xl font-semibold text-[#DAA520]/90 mb-3">
              9. Changes to This Policy
            </h2>
            <p className="text-[#C0C0C0]/80 leading-relaxed">
              We may update this policy as the site evolves. Material changes will be noted by
              updating the effective date above. Continued use of the site after changes constitutes
              acceptance.
            </p>
          </section>

        </article>
      </div>
    </main>
  );
}
